### ISSUE TITLE
[BUG] Compatibility with GD-Roulette Mod

### ISSUE THREAD

**Issue by fteod2** [undefined06855/AutoCheckpoint#2]
(Android-64)
When playing a level using the roulette in the mod "GD-Roulette" (by SpaghettDev), the game crashes when you get a new best.

To Reproduce:
1. Play a level of any difficulty in GD-Roulette's roulette feature.
2. Get a new best
3. The game will crash

Expected behavior:
The game should not crash when getting a new best in a roulette level in GD-Roulette. (when AutoCheckpoint is installed.)

Desktop:
 - Chrome OS
 - Version: Version 121.0.6167.159 (Official Build) (64-bit)
 
 Mod Version: 1.0.0

**Comment by undefined06855** [comment]
I'll test later but how on earth does that interfere 😭

**Comment by undefined06855** [comment]
I can't seem to get the game to crash, are you sure it's GD-Roulette and AutoCheckpoint? What other mods do you have installed

**Comment by undefined06855** [comment]
ok i genuinely have no idea what on earth is causing this, i'll add gdroulette as an incompatibility but unless you can figure it out from [this crash dump](https://cdn.discordapp.com/attachments/1102573869832876042/1208480952767090718/Crash_2024-02-17_18.29.02.dmp.txt?ex=65e37097&is=65d0fb97&hm=a59033076a759e00972162ade67bd718c509f56533fd64f14c5b77dcdff9e8c2&) then idk

**Comment by fteod2** [comment]
btw the other mods i had installed are 
-Jukebox
-Node ids
-BetterInfo
-QOLMod
-Icon Profile 2.2
-Backup
-GD-Roulette
-BetterEdit
-Custom Name
-Blending Glow
-More Settings Button
-NoMoreGames
-Goodbye Unnecessary Buttons
-Demons In Garage 2.2
-Gradient Pages 

maybe that can help
