### ISSUE TITLE
You get kicked out to the menu before finishing the level in normal and practice mode

### ISSUE THREAD

**Issue by JoJoBollo** [undefined06855/AutoCheckpoint#3]
I checked and this only happens when you have the mod enabled on geode. What happens is that when you're about to finish some specific levels, it will kick you out to the level selector screen before reaching the 100% line. This means that the game won't pick the achievement of the level and you don't win.
Some levels where this happened to me was Aftersonic(12379596) and Zircon(76821414)
This is a video example of it where it happens:

https://github.com/undefined06855/AutoCheckpoint/assets/160356042/61a7d456-6b66-4052-b4f7-dc7497c8748b

**_(it doesn't save the 100% practice level finished, it only shows it here like that because I did the practice before without the mod)_**
It doesn't happen in all levels but I think that this error is presented in a lot of them.
This also happened to a friend of mine, so I don't think is a problem of mine
Thank you for your time <3

**Comment by undefined06855** [comment]
yeah I've seen this before, gd's anticheat does some weird stuff sometimes

~~can you download the build output from [here](https://github.com/undefined06855/AutoCheckpoint/actions/runs/7948191477) and see if that fixes the issue?~~ nevermind I don't think that will fix your issue I have no idea

**Comment by JoJoBollo** [comment]
> yeah I've seen this before, gd's anticheat does some weird stuff sometimes
> 
> ~can you download the build output from [here](https://github.com/undefined06855/AutoCheckpoint/actions/runs/7948191477) and see if that fixes the issue?~ nevermind I don't think that will fix your issue I have no idea

Maybe it could be because the game detects weird issues sometimes? idk

**Comment by undefined06855** [comment]
im going to close this as not planned because i have no idea why anticheat is silly but ill definitely keep this in mind i've had like 3 gd messages about this bug😭
