### ISSUE TITLE
Anticheat being triggered in normal and practice mode

### ISSUE THREAD

**Issue by Joh3BL** [undefined06855/AutoCheckpoint#6]
Don't know why this happens, just installed a lot of mods and the level crashes when I reach the end on these levels:

100993356
100279572
100205827

All of these levels are platformers btw.

**Comment by undefined06855** [comment]
wdym by crashing? I assume it's just the anticheat being weird but I'm working on that

**Comment by Joh3BL** [comment]
Yeah, it's probably the anticheat. Will look more into it tomorrow

**Comment by undefined06855** [comment]
afaik this has been fixed in the latest release, if not then please reopen
