### ISSUE TITLE
Crashing when collecting any number of mana orbs

### ISSUE THREAD

**Issue by Carlcooper** [undefined06855/AutoCheckpoint#7]
Whenever I collect mana orb(s) with the Autocheckpoint mod, my game crashes a few seconds later.

Crash log:
[Geode 2024-03-07 16.03.11.log](https://github.com/undefined06855/AutoCheckpoint/files/14531490/Geode.2024-03-07.16.03.11.log)

**Comment by undefined06855** [comment]
are you on android? this only seems to happen on android 

also that's the log not the crash log

**Comment by Carlcooper** [comment]
Yes, I am on android and I apologize for attaching the wrong file. I attached the crashlog.

[Crash 2024-03-08 09.46.50.dmp](https://github.com/undefined06855/AutoCheckpoint/files/14541508/Crash.2024-03-08.09.46.50.dmp)

**Comment by undefined06855** [comment]
i think it's been fixed, see [these messages](https://discord.com/channels/911701438269386882/911702353546215524/1221425085231927347) (if you're in the geode discord server)

**Comment by undefined06855** [comment]
yep it was fixed
